name: Push docker images to Docker Hub

on:
  push:
    branches: [ "main", "version/**" ]
  pull_request:
    branches: [ "main", "version/**" ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./front-end-react/Dockerfile
            image: jesusptb/front-end-react
            context: ./front-end-react
          - dockerfile: ./order-service/Dockerfile
            image: jesusptb/order-service
            context: ./order-service
          - dockerfile: ./user-service/Dockerfile
            image: jesusptb/user-service
            context: ./user-service

    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag from branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          TAG=$(echo ${GITHUB_REF#refs/heads/} | awk -F/ '{print $NF}')
          if [[ $BRANCH_NAME == "main" ]]; then
            TAG=latest
          fi
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Get tag from branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          TAG=$(echo ${GITHUB_REF#refs/heads/} | awk -F/ '{print $NF}')
          if [[ $BRANCH_NAME == "main" ]]; then
            TAG=latest
          fi
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:${{ env.TAG }}