name: Push docker images to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push front-end-react image
        uses: docker/build-push-action@v5
        with:
          context: ./front-end-react
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/front-end-react:latest
      - name: Build and push order-service image
        uses: docker/build-push-action@v5
        with:
          context: ./order-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
      - name: Build and push user-service image
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest